name: Validate numpy docstrings

on:
  pull_request:
  push:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron: "0 */72 * * *"

jobs:
  npdocval:
    runs-on: ${{ matrix.os }}
    environment:
      name: test
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10"]
        os: [ubuntu-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@4

      - name: set up python '3.10'
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install --only-binary=all numpy
          python -m pip install numpydoc
          python -m pip install -e "."

      - name: Validate numpy docstrings
        run: |
          python dev/scripts/numpydoc_validate.py
